[package]
name = "aws-lambda-rust"
version = "0.1.0"
edition = "2018"

[dependencies]
lambda-web = { version = "0.1.8", features=["rocket05"] }
rocket = "0.5.0-rc.1"

[[bin]]
name = "bootstrap"
path = "src/main.rs"
