service: "aws-lambda-rust" # NOTE: update this with your service name
provider:
  name: aws
  profile: opszero
  runtime: provided.al2
  region: us-west-2
  memorySize: 128
  deploymentBucket:
    name: infra.opszero.com
  environment:
    DYNAMODB_TABLE_NAME: ${self:service}-${sls:stage}
  # iamRoleStatements:
  #   - Effect: "Allow"
  #     Action:
  #     - dynamodb:*
  #     Resource:
  #       Fn::GetAtt:
  #         - oneTable
  #         - Arn
  #   - Effect: "Allow"
  #     Action:
  #     - s3:*
  #     Resource:
  #       Fn::Join:
  #         - ""
  #         - - "arn:aws:s3:::"
  #           - "Ref" : "setupname"
  #           - '/*'

functions:
  flywheel:
    handler: flywheel
    timeout: 29
    memorySize: 128
    url:
      cors: true

package:
  patterns:
    - '!node_modules/**'
    - '!target/**'

# resources:
#   Resources:
#     oneTable:
#       Type: AWS::DynamoDB::Table
#       Properties:
#         TableName: ${self:service}-${sls:stage}
#         AttributeDefinitions:
#           - AttributeName: pk
#             AttributeType: S
#           - AttributeName: sk
#             AttributeType: S
#         KeySchema:
#           - AttributeName: pk
#             KeyType: HASH
#           - AttributeName: sk
#             KeyType: RANGE
#         ProvisionedThroughput:
#           ReadCapacityUnits: 1
#           WriteCapacityUnits: 1
#     s3bucket:
#       Type: AWS::S3::Bucket
#       Properties:
#         BucketName: setupname
#         AccessControl: PublicRead
#         WebsiteConfiguration:
#           IndexDocument: index.html
